//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMMSLoadExcelFiles
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class HMMSEntitiesDB : DbContext
    {
        public HMMSEntitiesDB()
            : base("name=HMMSEntitiesDB")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<INV> INVs { get; set; }
        public virtual DbSet<ISU> ISUs { get; set; }
        public virtual DbSet<MXQ> MXQs { get; set; }
        public virtual DbSet<NOP> NOPs { get; set; }
        public virtual DbSet<ORD> ORDs { get; set; }
        public virtual DbSet<QOH> QOHs { get; set; }
        public virtual DbSet<TRN> TRNs { get; set; }
        public virtual DbSet<AUL> AULs { get; set; }
        public virtual DbSet<LOG> LOGs { get; set; }
    
        public virtual int AULCopytoHistory()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AULCopytoHistory");
        }
    
        public virtual int INVCopytoHistory()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("INVCopytoHistory");
        }
    
        public virtual int ISUCopytoHistory()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ISUCopytoHistory");
        }
    
        public virtual int MXQCopytoHistory()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("MXQCopytoHistory");
        }
    
        public virtual int NOPCopytoHistory()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("NOPCopytoHistory");
        }
    
        public virtual int ORDCopytoHistory()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ORDCopytoHistory");
        }
    
        public virtual int QOHCopytoHistory()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("QOHCopytoHistory");
        }
    
        public virtual int TRNCopytoHistory()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("TRNCopytoHistory");
        }
    }
}
